
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Backbutton from "@/components/Backbutton";
import NextButton from "@/components/NextButton";
import ReloadButton from "@/components/ReloadButton";
import { SaleOptionProvider } from '@/context/SaleOptionContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SaleOptionProvider>
    <div className="flex items-center gap-4 p-4 bg-gray-100 shadow-md sticky top-0 z-50">
            <Backbutton />
            <ReloadButton />
          </div>
        {children}
        </SaleOptionProvider>
      </body>
    </html>
  );
}
